In [35]:
from sklearn import preprocessing

import pandas as pd


data=pd.DataFrame( [
    ["utter pradesh",43534,3334,3533,4] ,
    ["uttrakhand",2234,204,2543,5] ,
    ["himachal",4345,224,3383,6] ,
    ["hariyana",9534,330,300,2] ,
    ["rajasthan",2334,324,1000,1] ,

    ],
    columns=["state","confirmed","death","recovered","state_N"],
              
                 )
 
data

state  confirmed  death  recovered  state_N
0  utter pradesh      43534   3334       3533        4
1     uttrakhand       2234    204       2543        5
2       himachal       4345    224       3383        6
3       hariyana       9534    330        300        2
4      rajasthan       2334    324       1000        1

In [14]:
iris['data'][:5]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [29]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
data['state_N']=labelencoder.fit_transform(data['state'])
data


state  confirmed  death  recovered  state_N
0  utter pradesh      43534   3334       3533        3
1     uttrakhand       2234    204       2543        4
2       himachal       4345    224       3383        1
3       hariyana       9534    330        300        0
4      rajasthan       2334    324       1000        2

In [32]:
x=pd.get_dummies(data["state"],prefix="state",drop_first=True)

In [33]:
x

state_himachal  state_rajasthan  state_utter pradesh  state_uttrakhand
0               0                0                    1                 0
1               0                0                    0                 1
2               1                0                    0                 0
3               0                0                    0                 0
4               0                1                    0                 0

In [40]:
import numpy as np

In [53]:
x=np.array([[1,2,0],[2,-2,3],[1,0,2]])
x

array([[ 1,  2,  0],
       [ 2, -2,  3],
       [ 1,  0,  2]])

In [56]:
m=x.mean(axis=0)
m

array([1.33333333, 0.        , 1.66666667])

In [57]:
s=x.std(axis=0)
s

array([0.47140452, 1.63299316, 1.24721913])

In [62]:
scaled_x=preprocessing.scale(x)
mscaled_x=scaled_x.mean(axis=0)
sscaled_x=scaled_x.std(axis=0)

In [64]:
print(mscaled_x)
print(sscaled_x)

[ 1.48029737e-16  0.00000000e+00 -5.55111512e-17]
[1. 1. 1.]


# scaling

In [68]:
data_scaler=preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled=data_scaler.fit_transform(x)
data_scaled

array([[0.        , 1.        , 0.        ],
       [1.        , 0.        , 1.        ],
       [0.        , 0.5       , 0.66666667]])

# normalization

In [70]:
data_n=preprocessing.normalize(x,norm='l1')
data_n

array([[ 0.33333333,  0.66666667,  0.        ],
       [ 0.28571429, -0.28571429,  0.42857143],
       [ 0.33333333,  0.        ,  0.66666667]])