# Binarisation


In [3]:
import numpy as np
from sklearn import preprocessing
input_data = np.array([
   [2.1, -1.9, 5.5],
   [-1.5, 2.4, 3.5],
   [0.5, -7.9, 5.6],
   [5.9, 2.3, -5.8]]
)

In [4]:
data_binarized = preprocessing.Binarizer(threshold=0.5).transform(input_data)
print("\nBinarized data:\n", data_binarized)


Binarized data:
 [[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


# Mean Removal

In [5]:

#displaying the mean and the standard deviation of the input data
print("Mean =", input_data.mean(axis=0))
print("Stddeviation = ", input_data.std(axis=0))
#Removing the mean and the standard deviation of the input data

data_scaled = preprocessing.scale(input_data)
print("Mean_removed =", data_scaled.mean(axis=0))
print("Stddeviation_removed =", data_scaled.std(axis=0))

Mean = [ 1.75  -1.275  2.2  ]
Stddeviation =  [2.71431391 4.20022321 4.69414529]
Mean_removed = [1.11022302e-16 0.00000000e+00 0.00000000e+00]
Stddeviation_removed = [1. 1. 1.]


In [6]:
data_scaled

array([[ 0.12894603, -0.14880162,  0.70300338],
       [-1.19735598,  0.8749535 ,  0.27694073],
       [-0.46052153, -1.57729713,  0.72430651],
       [ 1.52893149,  0.85114524, -1.70425062]])

In [2]:
import joblib
a=joblib.load('iris_classifier_knn.joblib')

In [8]:
a.predict([[0.2,0.3,1,0.3]])

array([0])

In [1]:
from sklearn import preprocessing

In [2]:
import numpy as np

In [28]:
x_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                  [ 0.,  1., -4.]])

In [29]:
x_train

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -4.]])

In [30]:
scaler=preprocessing.StandardScaler().fit(x_train)

In [31]:
scaler

StandardScaler()

In [32]:
scaler.mean_

array([ 1.        ,  0.        , -0.66666667])

In [33]:
scaler.scale_


array([0.81649658, 0.81649658, 2.49443826])

In [34]:
scaledX=preprocessing.StandardScaler().fit_transform(x_train)

In [35]:
scaledX

array([[ 0.        , -1.22474487,  1.06904497],
       [ 1.22474487,  0.        ,  0.26726124],
       [-1.22474487,  1.22474487, -1.33630621]])

In [36]:
scaledX.min(axis=0)

array([-1.22474487, -1.22474487, -1.33630621])

In [37]:
 
scaledX.max(axis=0)

array([1.22474487, 1.22474487, 1.06904497])

In [38]:
scaledX.mean(axis=0)

array([ 0.00000000e+00,  0.00000000e+00, -7.40148683e-17])

In [39]:
scaledX.std(axis=0)

array([1., 1., 1.])

In [40]:
# how to use pipeline


In [62]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split

In [63]:
x,y=make_classification(random_state=42)

In [64]:
x

array([[-2.02514259,  0.0291022 , -0.47494531, ..., -0.33450124,
         0.86575519, -1.20029641],
       [ 1.61371127,  0.65992405, -0.15005559, ...,  1.37570681,
         0.70117274, -0.2975635 ],
       [ 0.16645221,  0.95057302,  1.42050425, ...,  1.18901653,
        -0.55547712, -0.63738713],
       ...,
       [-0.03955515, -1.60499282,  0.22213377, ..., -0.30917212,
        -0.46227529, -0.43449623],
       [ 1.08589557,  1.2031659 , -0.6095122 , ..., -0.3052247 ,
        -1.31183623, -1.06511366],
       [-0.00607091,  1.30857636, -0.17495976, ...,  0.99204235,
         0.32169781, -0.66809045]])

In [65]:
y

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0])

In [66]:
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=42)

In [70]:
X_train.shape
X_test.shape

(25, 20)

In [71]:
pipe = make_pipeline(StandardScaler(), LogisticRegression())

In [72]:
pipe

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [73]:
 pipe.fit(X_train, y_train) 

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [74]:
pipe.score(X_test, y_test)

0.96