# Binarisation


In [3]:
import numpy as np
from sklearn import preprocessing
input_data = np.array([
   [2.1, -1.9, 5.5],
   [-1.5, 2.4, 3.5],
   [0.5, -7.9, 5.6],
   [5.9, 2.3, -5.8]]
)

In [4]:
data_binarized = preprocessing.Binarizer(threshold=0.5).transform(input_data)
print("\nBinarized data:\n", data_binarized)


Binarized data:
 [[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


# Mean Removal

In [5]:

#displaying the mean and the standard deviation of the input data
print("Mean =", input_data.mean(axis=0))
print("Stddeviation = ", input_data.std(axis=0))
#Removing the mean and the standard deviation of the input data

data_scaled = preprocessing.scale(input_data)
print("Mean_removed =", data_scaled.mean(axis=0))
print("Stddeviation_removed =", data_scaled.std(axis=0))

Mean = [ 1.75  -1.275  2.2  ]
Stddeviation =  [2.71431391 4.20022321 4.69414529]
Mean_removed = [1.11022302e-16 0.00000000e+00 0.00000000e+00]
Stddeviation_removed = [1. 1. 1.]


In [6]:
data_scaled

array([[ 0.12894603, -0.14880162,  0.70300338],
       [-1.19735598,  0.8749535 ,  0.27694073],
       [-0.46052153, -1.57729713,  0.72430651],
       [ 1.52893149,  0.85114524, -1.70425062]])

In [2]:
import joblib
a=joblib.load('iris_classifier_knn.joblib')

In [8]:
a.predict([[0.2,0.3,1,0.3]])

array([0])